name: Test Install Script

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
      - test-install-script
    paths:
      - '.github/workflows/test-install-script.yml'
      - 'install.sh'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/test-install-script.yml'
      - 'install.sh'

jobs:
  linux:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-22.04, archlinux, wsl]
        include:
          - os: ubuntu-latest
            image: ubuntu:latest
          - os: ubuntu-22.04
            image: ubuntu:22.04
          - os: archlinux
            image: archlinux:latest
          - os: wsl
            image: mcr.microsoft.com/wsl:latest

    name: ${{ matrix.os }}
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.image }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Make install.sh Executable
        run: chmod +x install.sh

      - name: Run Installation Script
        run: ./install.sh

  macos:
    name: MacOS Latest
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Make install.sh Executable
        run: chmod +x install.sh

      - name: Run Installation Script
        run: ./install.sh
